rozcestnik update
v tomhle stavu mi to hází chybu:

Warning:
require(C:\xampp\htdocs\caravans\caravans/../vendor/autoload.php):
failed to open stream: No such file or directory in
C:\xampp\htdocs\caravans\caravans\bootstrap.php on line 3

Fatal error: require(): Failed opening required
'C:\xampp\htdocs\caravans\caravans/../vendor/autoload.php'
(include_path='.;C:\xampp\php\PEAR') in
C:\xampp\htdocs\caravans\caravans\bootstrap.php on line 3

ale to už když jsem to zkopčil z posledního updatu - Merge remote-
tracking branch 'origin/ .....
ten update tam hodil nějaké komenty, ale to jsem opravil